{
 "title": "API Node",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{job=\"api\", instance=\"10.104.0.3:9100\", mode!=\"idle\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"api\", instance=\"10.104.0.3:9100\"} - node_memory_MemFree_bytes{job=\"api\", instance=\"10.104.0.3:9100\"} - node_memory_Cached_bytes{job=\"api\", instance=\"10.104.0.3:9100\"} - node_memory_Buffers_bytes{job=\"api\", instance=\"10.104.0.3:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"api\", instance=\"10.104.0.3:9100\"}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"api\", instance=\"10.104.0.3:9100\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"api\", instance=\"10.104.0.3:9100\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"10.104.0.3:9100\",job=\"api\"}[5m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"api\",instance=\"10.104.0.3:9100\"}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "description": "Transactions Per Second",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_response_time_seconds_count{job=\"api-golang\", instance=\"10.104.0.3:8000\"}[10s])) by (job, instance)",
     "legendFormat": "total-req-rate"
    },
    {
     "expr": "sum(rate(http_requests_total{job=\"api-golang\", instance=\"10.104.0.3:8000\"}[10s])) by (job, instance) - sum(rate(http_requests_total{job=\"api-golang\", instance=\"10.104.0.3:8000\", status=\"200\"}[10s])) by (job, instance)",
     "legendFormat": "error-req-rate"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * sum(rate(http_response_time_seconds_sum{job=\"api-golang\", instance=\"10.104.0.3:8000\"}[1m])) by (job, instance) /\nsum(rate(http_response_time_seconds_count{job=\"api-golang\", instance=\"10.104.0.3:8000\"}[1m])) by (job, instance)",
     "legendFormat": "avg-res-time"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * histogram_quantile(0.5, sum(rate(http_response_time_seconds_bucket{job=\"api-golang\", instance=\"10.104.0.3:8000\"}[1m])) by (le))",
     "legendFormat": "latency-50-percentile"
    },
    {
     "expr": "1000 * histogram_quantile(0.95, sum(rate(http_response_time_seconds_bucket{job=\"api-golang\", instance=\"10.104.0.3:8000\"}[1m])) by (le))",
     "legendFormat": "latency-95-percentile"
    },
    {
     "expr": "1000 * histogram_quantile(0.99, sum(rate(http_response_time_seconds_bucket{job=\"api-golang\", instance=\"10.104.0.3:8000\"}[1m])) by (le))",
     "legendFormat": "latency-99-percentile"
    }
   ]
  }
 ]
}