{
 "title": "API Node v2",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without(mode) (irate(node_cpu_seconds_total{job=\"api\", instance=\"10.104.0.3:9100\", mode!=\"idle\"}[1m]))",
     "legendFormat": "cpu_usage"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - ((node_memory_MemFree_bytes{job=\"api\", instance=\"10.104.0.3:9100\"} + node_memory_Cached_bytes{job=\"api\", instance=\"10.104.0.3:9100\"} + node_memory_Buffers_bytes{job=\"api\", instance=\"10.104.0.3:9100\"})/node_memory_MemTotal_bytes{job=\"api\", instance=\"10.104.0.3:9100\"})",
     "legendFormat": "memory_usage"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "sum without(device) (irate(node_network_receive_bytes_total{instance=\"10.104.0.3:9100\",job=\"api\"}[1m]))",
     "legendFormat": "bandwidth_inbound"
    },
    {
     "expr": "sum without(device) (irate(node_network_transmit_bytes_total{instance=\"10.104.0.3:9100\",job=\"api\"}[1m]))",
     "legendFormat": "bandwidth_outbound"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "description": "Transactions Per Second",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_response_time_seconds_count{job=\"api-golang\", instance=\"10.104.0.3:8000\"}[1m])) by (job, instance)",
     "legendFormat": "tps"
    },
    {
     "expr": "sum(rate(http_requests_total{job=\"api-golang\", instance=\"10.104.0.3:8000\"}[1m])) by (job, instance) - sum(rate(http_requests_total{job=\"api-golang\", instance=\"10.104.0.3:8000\", status=\"200\"}[1m])) by (job, instance)",
     "legendFormat": "tps_error"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * sum(rate(http_response_time_seconds_sum{job=\"api-golang\", instance=\"10.104.0.3:8000\"}[1m])) by (job, instance) /\nsum(rate(http_response_time_seconds_count{job=\"api-golang\", instance=\"10.104.0.3:8000\"}[1m])) by (job, instance)",
     "legendFormat": "response_time"
    }
   ]
  }
 ]
}